In [1]:
import numpy as np

In [5]:
u = np.arange(1, 4)
v = np.arange(6, 9)

### Inner product

$(u, v) = \sum\limits_i u_i \cdot v_i = u^Tv$

In [10]:
u.dot(v)

44

In [11]:
(u * v).sum()

44

In [19]:
def vector_vector_mult(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    res = 0.0
    for i in range(n):
        res += u[i] * v[i]
    return res

In [20]:
vector_vector_mult(u, v)

44.0

In [21]:
v.dot(u)

44

### Matrix-vector multiplication

In [50]:
U = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [1, 0, 0, 1]
])

v = np.array([1, 0, 0, 1])

In [53]:
def matrix_vector_mult(U, v):
    assert U.shape[1] == v.shape[0]
    
    res = np.zeros(U.shape[0])
    
    for i in range(U.shape[0]):
        res[i] = vector_vector_mult(U[i], v)
        
    return res

In [54]:
matrix_vector_mult(U, v)

array([5., 7., 2.])

In [56]:
U.dot(v) - matrix_vector_mult(U, v)

array([0., 0., 0.])

### Matrix-matrix multiplication

In [57]:
A = np.array([
    [1, 2, 3, 4],
    [3, 0, 1, 1],
    [1, 1, 1, 1]
])
B = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5],
    [5, 6, 7]
])

In [68]:
def matrix_matrix_mult(A, B):
    assert A.shape[1] == B.shape[0]
    
    n = A.shape[0]
    
    res = np.zeros((A.shape[0], B.shape[1]))
    
    for i in range(n):
        res[:, i] = matrix_vector_mult(A, B[:, i])
    
    return res

In [69]:
A.dot(B) - matrix_matrix_mult(A, B)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
matrix_matrix_mult(A, B)

array([[34., 44., 54.],
       [11., 16., 21.],
       [11., 15., 19.]])

In [71]:
A.dot(B) - B.dot(A)

ValueError: operands could not be broadcast together with shapes (3,3) (4,4) 

### Identity matrix

In [37]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Inverse matrix

In [44]:
np.linalg.inv(U[:, 0:3]).dot(U[:,0:3])

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 4.44089210e-16,  1.00000000e+00,  1.77635684e-15],
       [-1.11022302e-16,  0.00000000e+00,  1.00000000e+00]])

In [45]:
U[:, 3]

array([4, 5, 1])